from __future__ import annotations

# Generated by pydantic-fixturegen v1.2.0 | seed=unknown | model-digest=fac509b5177688e65438f2910194553c6a3046daadd7cf488e2149db3921c85b | cases=3 | models=app.models.order.OrderEnvelope | return=model | scope=session | style=factory | time_anchor=2025-01-01T00:00:00+00:00

import pytest
from typing import Any, Callable
from app.models.order import OrderEnvelope


@pytest.fixture(
    scope="session",
    params=[
        {
            "audit_trail": [
                {
                    "action": "iKZzsdd",
                    "actor": "ops@example.com",
                    "at": "2025-01-01T00:00:00Z",
                    "metadata": {"RkENZu": "LbSzGJ", "nGTzfW": "BMchsYT"},
                },
                {
                    "action": "CBlQmEDeKkWba",
                    "actor": "ops@example.com",
                    "at": "2025-01-01T00:00:00Z",
                    "metadata": {"jOd": "bAYkc", "oEXB": "YgJpxA", "tUSmSV": "ZI"},
                },
                {
                    "action": "jp",
                    "actor": "ops@example.com",
                    "at": "2025-01-01T00:00:00Z",
                    "metadata": {"YwTq": "sZvk"},
                },
            ],
            "captures": [
                {
                    "amount": {"amount": "4.74", "currency": "SEK"},
                    "capture_id": "00000000-0000-4000-8000-000000000000",
                    "captured_at": "2025-01-01T00:00:00Z",
                    "failure_reason": "heJlltOygmzT",
                    "intent_id": "00000000-0000-4000-8000-000000000000",
                    "requested_at": "2025-01-01T00:00:00Z",
                    "retries": 2,
                    "status": "pending",
                }
            ],
            "created_at": "2025-01-01T00:00:00Z",
            "customer": {
                "audit_trail": [
                    {
                        "action": "oIyoU",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"WBFR": "enLWQtc"},
                    },
                    {
                        "action": "ioQRAUmzPjeQAJes",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"PdJ": "jgToFkP", "sNyEN": "JXr"},
                    },
                    {
                        "action": "bFjmOBZL",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"NRLwaV": "ZRdMkOcT"},
                    },
                ],
                "billing_address": {
                    "city": "CaxwBVzU",
                    "country": "LN",
                    "line1": "cRVVUqZIBNgpQwu",
                    "line2": "kScTyNSfKvBH",
                    "postal_code": "Xjc",
                },
                "created_at": "2025-01-01T00:00:00Z",
                "email": "s61chq_9@h3g40s.io",
                "id": "00000000-0000-4000-8000-000000000000",
                "loyalty_tier": "bronze",
                "marketing_opt_in": False,
                "primary_phone": "+57197198",
                "risk_score": 0.8160515735074113,
                "shipping_address": {
                    "city": "fNBae",
                    "country": "XH",
                    "line1": "Zoyz",
                    "line2": "uewXpBvjLlae",
                    "postal_code": "XeSS",
                },
                "tags": ["QANdhnjq", "xMwAKRW", "XK"],
                "updated_at": "2025-01-01T00:00:00Z",
            },
            "delivery": {
                "geo_fence": {"lat": 85.35811598106565, "lon": 92.02771310220032, "radius_m": 4030},
                "handoff_instructions": "oNswZXxjqP",
                "preference": "pickup",
            },
            "gift_message": "bplaXuiEVhxEVt",
            "items": [
                {
                    "discounts": [
                        {"amount": {"amount": "7.19", "currency": "SEK"}, "description": "vccnq"},
                        {
                            "amount": {"amount": "9.42", "currency": "SEK"},
                            "description": "PctgCSqzFjOirc",
                        },
                    ],
                    "quantity": 32,
                    "selected_addons": ["dM", "Tii", "VW"],
                    "variant": {
                        "attributes": [
                            {"name": "ZyowvaVwAYDP", "value": "qnEnqxug"},
                            {"name": "IbZt", "value": "k"},
                        ],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "zdnihvwM",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["ujxaC", "r"],
                                "url": "https://qlnx1.org/-8nmo8ua/15d",
                            }
                        ],
                        "price": {"amount": "3.01", "currency": "SEK"},
                        "sku": "N1NGKM",
                        "title": "JTAgfjyCfCkGTvRX",
                    },
                },
                {
                    "discounts": [
                        {"amount": {"amount": "4.13", "currency": "SEK"}, "description": "AVc"}
                    ],
                    "quantity": 19,
                    "selected_addons": ["I", "z"],
                    "variant": {
                        "attributes": [
                            {"name": "HZivEqApPnLAKS", "value": "CzJhQPde"},
                            {"name": "M", "value": "lSCllNEzUXp"},
                            {"name": "TdBRvGunmpDB", "value": "RxkyWJLCCliHh"},
                        ],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "ttBhyUXaeEPsLCg",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["EiVGfKI", "jdycw"],
                                "url": "https://dtfu.org/7byj",
                            },
                            {
                                "alt_text": "LncZlg",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["cy", "FShsc", "U"],
                                "url": "https://68bylpo3h9.com/hp_slm/1j9y/t97",
                            },
                        ],
                        "price": {"amount": "6.42", "currency": "SEK"},
                        "sku": "WZ9ISN7ZPS3",
                        "title": "RNLtvaBMt",
                    },
                },
                {
                    "discounts": [
                        {"amount": {"amount": "4.51", "currency": "SEK"}, "description": "QzKjR"}
                    ],
                    "quantity": 25,
                    "selected_addons": ["jBXRm", "dHjh", "DUFXKEj"],
                    "variant": {
                        "attributes": [{"name": "CivFsOsacYuf", "value": "vzutDD"}],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "UMwpBnFj",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["XQBzxm", "AVATQYr"],
                                "url": "https://8twjq6.dev/bqb6",
                            },
                            {
                                "alt_text": "kLJlpEfBBUtRR",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["OfUj", "gaQiFE"],
                                "url": "https://bozrc0e.com/p4p9mtpn",
                            },
                            {
                                "alt_text": "bAWRcPLWNTnNX",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["vb"],
                                "url": "https://kf84b9pow.io/sxebn1bz",
                            },
                        ],
                        "price": {"amount": "5.13", "currency": "SEK"},
                        "sku": "H8WPVLEFJN7J8",
                        "title": "gwhVDnn",
                    },
                },
            ],
            "notifications": [
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"XovQ": "oY"},
                    "recipient": "tv01x3g6@glp5ez2.com",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [{"locale": "wg-AL", "text": "EKSONimJSFytqhk"}],
                        "key": "rnnrx1c4xs48c9ob",
                        "subject": {"locale": "bc-ZB", "text": "PDZnRduPAQ"},
                    },
                },
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"OOBEj": "PwqZg"},
                    "recipient": "xhehz_jb@13k.net",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [
                            {"locale": "dn-WN", "text": "eXK"},
                            {"locale": "lg-DM", "text": "rmMWxf"},
                            {"locale": "vz-IW", "text": "mkNBhtMV"},
                        ],
                        "key": "_xirq",
                        "subject": {"locale": "tf-LX", "text": "lkiwFoG"},
                    },
                },
            ],
            "order_id": "00000000-0000-4000-8000-000000000000",
            "payment_intent": {
                "amount": {"amount": "3.79", "currency": "SEK"},
                "audit_trail": [
                    {
                        "action": "m",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"fGa": "x", "nNGKw": "XNNB"},
                    },
                    {
                        "action": "BFNc",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"rCKR": "uJX", "rebxRR": "osPQfV"},
                    },
                    {
                        "action": "NIuSiSqgDVeaVFA",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"WUPAop": "r", "ehmVtQ": "QY"},
                    },
                ],
                "created_at": "2025-01-01T00:00:00Z",
                "customer_id": "00000000-0000-4000-8000-000000000000",
                "expires_at": "2025-01-01T00:00:00Z",
                "intent_id": "00000000-0000-4000-8000-000000000000",
                "provider": "stripe",
                "statement_descriptor": "ZgHSCtDuusKKGbG",
                "updated_at": "2025-01-01T00:00:00Z",
            },
            "priority": "standard",
            "shipments": [
                {
                    "carrier": "r",
                    "destination": {
                        "city": "uhbpgIqsLIbGKU",
                        "country": "TM",
                        "line1": "KKujVkYEPPmrCf",
                        "line2": "eEnlu",
                        "postal_code": "gQkTA6XQ",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "CJZXDZR8G951OPKS",
                },
                {
                    "carrier": "ZUQDunJQTv",
                    "destination": {
                        "city": "LAkzkqFHg",
                        "country": "PY",
                        "line1": "xfnEYoOvWg",
                        "line2": "keYS",
                        "postal_code": "bC4dBt 8Au",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "64Y1097SY7ZO73C8",
                },
            ],
            "state_history": [
                {
                    "from_state": "draft",
                    "note": "VgpCktxt",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
                {
                    "from_state": "draft",
                    "note": "SozFRVjRvzUVrP",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
            ],
            "updated_at": "2025-01-01T00:00:00Z",
        },
        {
            "audit_trail": [
                {
                    "action": "MXngc",
                    "actor": "ops@example.com",
                    "at": "2025-01-01T00:00:00Z",
                    "metadata": {"DUpr": "GcJ", "Ebe": "rRkA"},
                },
                {
                    "action": "cpQWrAJPzyjMZZvL",
                    "actor": "ops@example.com",
                    "at": "2025-01-01T00:00:00Z",
                    "metadata": {"qccLU": "TT", "yci": "pxq"},
                },
            ],
            "captures": [
                {
                    "amount": {"amount": "2.57", "currency": "SEK"},
                    "capture_id": "00000000-0000-4000-8000-000000000000",
                    "captured_at": "2025-01-01T00:00:00Z",
                    "failure_reason": "PmdyNLKGXQMGiza",
                    "intent_id": "00000000-0000-4000-8000-000000000000",
                    "requested_at": "2025-01-01T00:00:00Z",
                    "retries": 0,
                    "status": "pending",
                },
                {
                    "amount": {"amount": "9.47", "currency": "SEK"},
                    "capture_id": "00000000-0000-4000-8000-000000000000",
                    "captured_at": "2025-01-01T00:00:00Z",
                    "failure_reason": "MsZtEQK",
                    "intent_id": "00000000-0000-4000-8000-000000000000",
                    "requested_at": "2025-01-01T00:00:00Z",
                    "retries": 2,
                    "status": "pending",
                },
            ],
            "created_at": "2025-01-01T00:00:00Z",
            "customer": {
                "audit_trail": [
                    {
                        "action": "NZSYQdNHEtFtHqcf",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"CvrsMd": "Qa", "zmeyi": "VwbwwP"},
                    },
                    {
                        "action": "NIKHPoja",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"Xryg": "Bcf"},
                    },
                ],
                "billing_address": {
                    "city": "GTLinxZvRlesvU",
                    "country": "WL",
                    "line1": "XZutmSmYXb",
                    "line2": "SjR",
                    "postal_code": "5P9fYS",
                },
                "created_at": "2025-01-01T00:00:00Z",
                "email": "ef6pvmd3@wevtk3.org",
                "id": "00000000-0000-4000-8000-000000000000",
                "loyalty_tier": "bronze",
                "marketing_opt_in": True,
                "primary_phone": "+124428142410",
                "risk_score": 0.10490555247195843,
                "shipping_address": {
                    "city": "h",
                    "country": "YK",
                    "line1": "ZVRIr",
                    "line2": "PMqBXDWX",
                    "postal_code": "3OTGP96N",
                },
                "tags": ["jhgUjkZZ"],
                "updated_at": "2025-01-01T00:00:00Z",
            },
            "delivery": {
                "geo_fence": {
                    "lat": 47.31886243901377,
                    "lon": -126.89078158688025,
                    "radius_m": 14351,
                },
                "handoff_instructions": "hTdJpfOws",
                "preference": "pickup",
            },
            "gift_message": "LDnkoadJdWYmcH",
            "items": [
                {
                    "discounts": [
                        {"amount": {"amount": "8.60", "currency": "SEK"}, "description": "Vo"},
                        {"amount": {"amount": "3.62", "currency": "SEK"}, "description": "NGxGi"},
                    ],
                    "quantity": 30,
                    "selected_addons": ["E", "g"],
                    "variant": {
                        "attributes": [
                            {"name": "AbjYncWmYghdC", "value": "fnJPfVDLheAAQUTH"},
                            {"name": "VBuIjIBk", "value": "H"},
                            {"name": "wpOPKyxsG", "value": "LZzqOKfSniRqNnK"},
                        ],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "kMJXmPQIZodEm",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["NDvoX"],
                                "url": "https://n3wopoed.com/qfhglo",
                            }
                        ],
                        "price": {"amount": "5.54", "currency": "SEK"},
                        "sku": "T64OEA05FMWLLQ",
                        "title": "BNwHwLaRbksmFg",
                    },
                }
            ],
            "notifications": [
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"YlL": "jblU", "bWQOKg": "dp", "xbxXu": "eFkAXoM"},
                    "recipient": "opngdlrv@00ag2kc6.net",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [
                            {"locale": "hx-ZZ", "text": "zmwzEz"},
                            {"locale": "wq-WM", "text": "WQEfQUIohgDhyNW"},
                            {"locale": "yv-CN", "text": "kaXXj"},
                        ],
                        "key": "7cjxt4ifqs0igddv",
                        "subject": {"locale": "nu-RL", "text": "Vk"},
                    },
                },
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"FcKM": "euojrC", "IcFWn": "JYbPj", "yjI": "QqCzg"},
                    "recipient": "1szk52kw@9e875pkwbc.org",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [{"locale": "fw-JV", "text": "c"}],
                        "key": "hqrqcr8ldlbtiy13",
                        "subject": {"locale": "hs-RR", "text": "EtPkiTNYpYgWHS"},
                    },
                },
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"itgenb": "umC"},
                    "recipient": "j2bwuv7k@y7yj2lxo.dev",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [
                            {"locale": "wn-TJ", "text": "igXYDih"},
                            {"locale": "gt-PK", "text": "JAmsvQRGS"},
                        ],
                        "key": "td",
                        "subject": {"locale": "qd-FB", "text": "tkinfsteEgpzE"},
                    },
                },
            ],
            "order_id": "00000000-0000-4000-8000-000000000000",
            "payment_intent": {
                "amount": {"amount": "4.74", "currency": "SEK"},
                "audit_trail": [
                    {
                        "action": "GpdriK",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"Xbkq": "RujlGuUQ", "vfeP": "VsO"},
                    }
                ],
                "created_at": "2025-01-01T00:00:00Z",
                "customer_id": "00000000-0000-4000-8000-000000000000",
                "expires_at": "2025-01-01T00:00:00Z",
                "intent_id": "00000000-0000-4000-8000-000000000000",
                "provider": "stripe",
                "statement_descriptor": "rDRNsIYDYpvvTjs",
                "updated_at": "2025-01-01T00:00:00Z",
            },
            "priority": "standard",
            "shipments": [
                {
                    "carrier": "cXhGLnjfbU",
                    "destination": {
                        "city": "nXadjmgmRFucNjv",
                        "country": "XY",
                        "line1": "aSioUADPEcdXea",
                        "line2": "CYIAy",
                        "postal_code": "KLcD-l",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "P8UVOK4XWG4O8THO",
                },
                {
                    "carrier": "d",
                    "destination": {
                        "city": "AHhCHfGVUuk",
                        "country": "ZN",
                        "line1": "NMYLMkYxvm",
                        "line2": "NntsQUQ",
                        "postal_code": "iZO",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "7M34D8OWASLCS4XN",
                },
            ],
            "state_history": [
                {
                    "from_state": "draft",
                    "note": "WOjVVurxQmjfA",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
                {
                    "from_state": "draft",
                    "note": "nx",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
            ],
            "updated_at": "2025-01-01T00:00:00Z",
        },
        {
            "audit_trail": [
                {
                    "action": "SSxTNJRAiaT",
                    "actor": "ops@example.com",
                    "at": "2025-01-01T00:00:00Z",
                    "metadata": {"IpEG": "tCFSxBXQ"},
                }
            ],
            "captures": [
                {
                    "amount": {"amount": "8.48", "currency": "SEK"},
                    "capture_id": "00000000-0000-4000-8000-000000000000",
                    "captured_at": "2025-01-01T00:00:00Z",
                    "failure_reason": "Y",
                    "intent_id": "00000000-0000-4000-8000-000000000000",
                    "requested_at": "2025-01-01T00:00:00Z",
                    "retries": 1,
                    "status": "pending",
                },
                {
                    "amount": {"amount": "5.17", "currency": "SEK"},
                    "capture_id": "00000000-0000-4000-8000-000000000000",
                    "captured_at": "2025-01-01T00:00:00Z",
                    "failure_reason": "XsppHWbFVL",
                    "intent_id": "00000000-0000-4000-8000-000000000000",
                    "requested_at": "2025-01-01T00:00:00Z",
                    "retries": 3,
                    "status": "pending",
                },
                {
                    "amount": {"amount": "5.52", "currency": "SEK"},
                    "capture_id": "00000000-0000-4000-8000-000000000000",
                    "captured_at": "2025-01-01T00:00:00Z",
                    "failure_reason": "VQigws",
                    "intent_id": "00000000-0000-4000-8000-000000000000",
                    "requested_at": "2025-01-01T00:00:00Z",
                    "retries": 2,
                    "status": "pending",
                },
            ],
            "created_at": "2025-01-01T00:00:00Z",
            "customer": {
                "audit_trail": [
                    {
                        "action": "n",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"MZq": "JBjWD", "ghi": "mOYiR", "qplQE": "VbSHaL"},
                    },
                    {
                        "action": "RZJv",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"BRMKfw": "wDxXHOBP", "Premoh": "Ne", "vMUOrj": "c"},
                    },
                ],
                "billing_address": {
                    "city": "eMRbjjybdEmjepR",
                    "country": "SP",
                    "line1": "nYjpL",
                    "line2": "Ux",
                    "postal_code": "-TR",
                },
                "created_at": "2025-01-01T00:00:00Z",
                "email": "7155s79e@j0xaqt8.com",
                "id": "00000000-0000-4000-8000-000000000000",
                "loyalty_tier": "bronze",
                "marketing_opt_in": False,
                "primary_phone": "36522236010",
                "risk_score": 0.8367002229797396,
                "shipping_address": {
                    "city": "r",
                    "country": "LH",
                    "line1": "fdNDma",
                    "line2": "w",
                    "postal_code": "SsahCr",
                },
                "tags": ["uDpfPcxH", "OaT", "i"],
                "updated_at": "2025-01-01T00:00:00Z",
            },
            "delivery": {
                "geo_fence": {
                    "lat": -29.71387072365271,
                    "lon": 95.28948157270509,
                    "radius_m": 13936,
                },
                "handoff_instructions": "pURmSyFjaj",
                "preference": "pickup",
            },
            "gift_message": "n",
            "items": [
                {
                    "discounts": [
                        {
                            "amount": {"amount": "5.56", "currency": "SEK"},
                            "description": "JgudXSTxV",
                        },
                        {"amount": {"amount": "9.37", "currency": "SEK"}, "description": "ojr"},
                    ],
                    "quantity": 5,
                    "selected_addons": ["l", "mJd", "pzeCQu"],
                    "variant": {
                        "attributes": [
                            {"name": "cqYmRjTAu", "value": "wnnbWN"},
                            {"name": "JTMdtbKxYHAqC", "value": "HxmzYXMVZycmf"},
                            {"name": "aWZFgG", "value": "EiDmakWWZbvIMByL"},
                        ],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "nkebJlaZKd",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["IFebjAaL", "DKuY"],
                                "url": "https://9ksz.net/tf8qtb2p",
                            }
                        ],
                        "price": {"amount": "9.95", "currency": "SEK"},
                        "sku": "3G7P6NRT6",
                        "title": "Fi",
                    },
                },
                {
                    "discounts": [
                        {"amount": {"amount": "9.02", "currency": "SEK"}, "description": "FNsRB"}
                    ],
                    "quantity": 19,
                    "selected_addons": ["lIk"],
                    "variant": {
                        "attributes": [
                            {"name": "jfYCXiwEBVRcMx", "value": "zruvB"},
                            {"name": "sy", "value": "HwXsWqWI"},
                        ],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "fJrUd",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["mHi", "nAEq", "Hvan"],
                                "url": "https://bc2ok7t.net/ro2nxs0/89y1_ra-/p4ee05z5",
                            }
                        ],
                        "price": {"amount": "9.88", "currency": "SEK"},
                        "sku": "TS0SZTC9D",
                        "title": "JxsJm",
                    },
                },
                {
                    "discounts": [
                        {
                            "amount": {"amount": "0.40", "currency": "SEK"},
                            "description": "ZZKZnAEnxHd",
                        },
                        {
                            "amount": {"amount": "8.57", "currency": "SEK"},
                            "description": "dWaXjEOgTYMzVNyc",
                        },
                        {
                            "amount": {"amount": "4.54", "currency": "SEK"},
                            "description": "tUYvYWhw",
                        },
                    ],
                    "quantity": 49,
                    "selected_addons": ["pQ", "Ittdx", "DzRBe"],
                    "variant": {
                        "attributes": [{"name": "lommUypwPbB", "value": "mbINttvJQSkfvPf"}],
                        "id": "00000000-0000-4000-8000-000000000000",
                        "media": [
                            {
                                "alt_text": "xKtyrFqzV",
                                "id": "00000000-0000-4000-8000-000000000000",
                                "tags": ["xKTZgohu", "GeYUxxBt", "pORRFe"],
                                "url": "https://5jn4tp.net/i4pfl",
                            }
                        ],
                        "price": {"amount": "9.88", "currency": "SEK"},
                        "sku": "C1D90XHFP10MD",
                        "title": "AiVDDB",
                    },
                },
            ],
            "notifications": [
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"BQGoBD": "aWtFok", "YKIIx": "JQwRmC", "zZcXt": "ZGCI"},
                    "recipient": "agw7nnop@mm42yp.net",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [{"locale": "iz-FJ", "text": "GKgYRwqrB"}],
                        "key": "ze85qsv_o10i6.jf",
                        "subject": {"locale": "al-PI", "text": "JhCTyQqX"},
                    },
                },
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"PUl": "EQt", "VkyeB": "FMbrzlHx"},
                    "recipient": "5p95k8o4@vjjq.org",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [
                            {"locale": "sf-DB", "text": "VkoLezxaHZIhn"},
                            {"locale": "ex-NX", "text": "ZhS"},
                        ],
                        "key": "zxiuqhz82taaqtae",
                        "subject": {"locale": "hr-DN", "text": "XiEhtObelYP"},
                    },
                },
                {
                    "channel": "email",
                    "event_id": "00000000-0000-4000-8000-000000000000",
                    "metadata": {"DNMmKj": "CFFTL", "TmMgY": "KrDvRW"},
                    "recipient": "3r9wm19f@i4ofpq.io",
                    "sent_at": "2025-01-01T00:00:00Z",
                    "template": {
                        "body": [
                            {"locale": "eu-XP", "text": "XmEt"},
                            {"locale": "mo-KD", "text": "XreNhGy"},
                            {"locale": "lh-OG", "text": "EmEBzdWe"},
                        ],
                        "key": ".yz.gmn3ozheu.hu",
                        "subject": {"locale": "kr-UY", "text": "tVOxycaIjZEeRSGH"},
                    },
                },
            ],
            "order_id": "00000000-0000-4000-8000-000000000000",
            "payment_intent": {
                "amount": {"amount": "0.96", "currency": "SEK"},
                "audit_trail": [
                    {
                        "action": "hdtorObjfZPJWovk",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"JYK": "CR", "eCR": "IZifvLfc"},
                    },
                    {
                        "action": "FEnQkxlC",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"nRznGl": "wnjOj"},
                    },
                    {
                        "action": "zojgiCNUGe",
                        "actor": "ops@example.com",
                        "at": "2025-01-01T00:00:00Z",
                        "metadata": {"HacRRf": "mKp", "QjZLCh": "aPXzhUYb", "TLs": "VCFZb"},
                    },
                ],
                "created_at": "2025-01-01T00:00:00Z",
                "customer_id": "00000000-0000-4000-8000-000000000000",
                "expires_at": "2025-01-01T00:00:00Z",
                "intent_id": "00000000-0000-4000-8000-000000000000",
                "provider": "stripe",
                "statement_descriptor": "BMcIXmJjuz",
                "updated_at": "2025-01-01T00:00:00Z",
            },
            "priority": "standard",
            "shipments": [
                {
                    "carrier": "digTsOzIFRRzXi",
                    "destination": {
                        "city": "j",
                        "country": "JB",
                        "line1": "cmwgvL",
                        "line2": "HcaVeTPUKbS",
                        "postal_code": "xN9GyReUu6",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "3682KEZMKWOJWWXK",
                },
                {
                    "carrier": "gteOCXLlNTsw",
                    "destination": {
                        "city": "JUEHEjx",
                        "country": "AM",
                        "line1": "HnYSaqDfmHaPTBFZ",
                        "line2": "SayNLFStJxQN",
                        "postal_code": "Q5C-unu",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "YWR54DKGDK5B02UW",
                },
                {
                    "carrier": "M",
                    "destination": {
                        "city": "e",
                        "country": "FT",
                        "line1": "FXfLo",
                        "line2": "dfAuRCglPmF",
                        "postal_code": "NtkZWD",
                    },
                    "leg_id": "00000000-0000-4000-8000-000000000000",
                    "promised_window": {
                        "end": "2025-01-01T00:00:00Z",
                        "start": "2025-01-01T00:00:00Z",
                    },
                    "tracking_code": "OZGUYWGA78Z3MB2N",
                },
            ],
            "state_history": [
                {
                    "from_state": "draft",
                    "note": "Geym",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
                {
                    "from_state": "draft",
                    "note": "oCLVFYaIrAJ",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
                {
                    "from_state": "draft",
                    "note": "R",
                    "occurred_at": "2025-01-01T00:00:00Z",
                    "to_state": "draft",
                },
            ],
            "updated_at": "2025-01-01T00:00:00Z",
        },
    ],
)
def order_envelope_factory(request) -> Callable[[dict[str, Any] | None], OrderEnvelope]:
    base_data = request.param

    def builder(overrides: dict[str, Any] | None = None) -> OrderEnvelope:
        data = dict(base_data)
        if overrides:
            data.update(overrides)
        return OrderEnvelope.model_validate(data)

    return builder
